version: 0.2

phases:
  install:
    commands:
      - echo "Switching to Java 21..."
        - export JAVA_HOME=/corretto/java21
        - export PATH=$JAVA_HOME/bin:$PATH
        - java -version
        - mvn -version
artifacts:
  files:
    - target/e-market-1.0.jar
